project_id = "xxaynwfseusnxlpukwnq"

[functions.summarize-contract]
verify_jwt = false

[functions.summarize-document]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.enrich-profile]
verify_jwt = false

[functions.generate-recurring-tasks]
verify_jwt = false